version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "6060:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6001:5000"
    environment:
      - FLASK_ENV=development
