version: '3'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development