apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      containers:
      - name: flask-backend
        image: gcr.io/carbon-mapp/dev-flask-app:latest
        ports:
        - containerPort: 6001
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/cloudsql/credentials.json